<div>
<div style="text-align: center;">
<span style="color: #d4340c; font-size: large;">
<strong>Hướng dẫn thanh toán</strong></span></div>
</div>
<div>




<div id="detail_news">
        <h1></h1>
       
        <div class="content_detail">
            <p><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>Các hình thức thanh toán khi mua hàng tại Thu thảo compuper<br></strong></span></p>
<p><span style="font-size: medium; font-family: arial,helvetica,sans-serif; color: #000000;">Khi quý khách mua hàng của Công ty , quý khách có thể thanh toán bằng các hình thức như sau:&nbsp;</span></p>
<p><span style="font-size: medium; font-family: arial,helvetica,sans-serif; color: #000000;">&nbsp;- Thanh toán bằng tiền mặt</span></p>
<p><span style="font-size: medium; font-family: arial,helvetica,sans-serif; color: #000000;">&nbsp;- Thanh toán bằng chuyển khoản</span></p>
<p><span style="font-size: medium; font-family: arial,helvetica,sans-serif; color: #000000;">&nbsp;- Các hình thức khác</span></p>
<p><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>1. Thanh toán bằng tiền mặt</strong></span></p>
<p><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>1.a.&nbsp; Thanh toán trực tiếp tại Công ty</strong></span></p>
<p><span style="font-size: medium; font-family: arial,helvetica,sans-serif; color: #000000;">Quý khách hàng vui lòng thanh toán trực tiếp tại công ty ngay khi mua hàng:<br> Trụ sở công ty : Số 10 Ngõ 117 Thái Hà, Đống Đa, Hà Nội.&nbsp;<br> </span></p>
<p><span style="font-size: medium; font-family: arial,helvetica,sans-serif; color: #000000;">- Ngay khi quý khách thanh toán xong, nhân viên kế toán sẽ gửi lại quý khách HĐTC và nhân viên kinh doanh sẽ hướng dẫn quý khách hình thức giao nhận hàng.</span></p>
<p><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>&nbsp;1.b. Thanh toán tại điểm giao hàng</strong></span></p>
<p><span style="font-size: medium; font-family: Arial,sans-serif;"><span style="color: #000000;">- Quý khách thanh toán cho nhân viên giao nhận toàn bộ hoặc phần còn lại của giá trị&nbsp;đơn hàng đã mua (nếu đã đặt cọc)</span><br><span style="color: #000000;"> - Nếu địa điểm giao hàng không nằm trong phạm vi được giao hàng miễn phí chúng tôi sẽ thu thêm chi phí vận chuyển (có thông báo trước với khách hàng)</span></span></p>
<p><span style="font-size: medium; font-family: Arial,sans-serif;"><span style="color: #000000;"><img style="display: block; margin-left: auto; margin-right: auto;" src="/images/giaohang.jpg" alt=""></span></span></p>
<p><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>2. Thanh toán bằng chuyển khoản</strong></span></p>
<p><span style="font-size: medium; font-family: arial,helvetica,sans-serif; color: #000000;">- Nếu địa điểm giao hàng là ngoại thành, ngoại tỉnh hoặc nội thành thành phố Hà Nội nhưng khác với địa điểm thanh toán (trong trường hợp Quý khách gửi quà, gửi hàng cho bạn bè, đối tác …) chúng tôi sẽ thu tiền trước 100% giá trị đơn hàng + phí vận chuyển theo cước phí tính trong chinh sách vận chuyển bằng phương thức chuyển khoản trước khi giao hàng</span></p>
<p><span style="font-size: medium; font-family: arial,helvetica,sans-serif; color: #000000;">Quý khách chuyển tiền cho chúng tôi vào một trong các&nbsp;tài khoản sau đây:</span></p>
<p><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>Ghi chú:</strong>&nbsp;Để hàng hóa và giá cả được chính xác, ngay sau khi quý khách chuyển tiền xin vui lòng fax giấy ủy nhiệm chi có dấu ngân hàng chuyển tiền để nhân viên kinh doanh làm căn cứ giữ hàng và giá tiền theo đúng thỏa thuận cho quý khách.</span></p>
<table border="1" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td style="padding: 0in 5.4pt; width: 509.4pt; border: 1pt solid black;" valign="top" width="679">
<p style="font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>1.<span style="font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span></span></strong><strong>Ngân hàng TNHH MTV Standard Chartered Việt Nam – Sở giao dịch Hà Nội</strong></span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>Bank name: Standard Chartered Bank (Viet Nam) Limited</strong></span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">Địa chỉ: P1810<strong><span class="Apple-converted-space">&nbsp;</span></strong>đến P1815, tòa tháp Keangnam Hanoi landmark, lô E6, khu đô thị mới<strong><span class="Apple-converted-space">&nbsp;</span></strong>Cầu Giấy, Mễ Trì, Từ Liêm, Thành Phố Hà Nội, Việt Nam</span></p>
<p style="margin: 0px 0px 6pt; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: justify;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">Address: Unit 1810 to 1815, Keangnam Hanoi landmark Tower, Plot E6, New Urban Area, Me Tri Commune, Tu Liem District, Ha Noi city, Viet Nam</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Tên Tài khoản Tiếng Việt: Công ty TNHH công nghệ tin học Thu Thảo</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Tên TK tiếng Anh: Ha Noi Computer Joint Stock Company</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Số Tài khoản VND:&nbsp; 88140711268</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Số Tài khoản USD: 88140711286</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Swift code: SCBLVNVX</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>Mã ngân hàng: 01604001</strong></span></p>
<p style="font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>2.<span style="font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span></span></strong><strong>Ngân hàng TMCP Ngoại Thương Việt Nam- Chi nhánh Tây Hồ</strong></span></p>
<p style="margin: 0px 0px 0px 1.5pt; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span></strong>Địa chỉ: 683 Lạc Long Quân- Tây Hồ- Hà Nội</span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="color: #000000; font-family: arial,helvetica,sans-serif; font-size: medium;">-&nbsp; Tên tài khoản: Công ty TNHH công nghệ tin học Thu Thảo</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Số tài khoản VND:<span class="Apple-converted-space">&nbsp;</span><strong>0991.000.000.930</strong></span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>Mã citad:<span class="Apple-converted-space">&nbsp;</span></strong><strong>01203001</strong></span></p>
<p style="font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>&nbsp;Ngân hàng&nbsp; Nông nghiệp và phát triển Nông thôn Việt Nam- Chi nhánh Hà Nội</strong></span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Địa chỉ: 77 Lạc Trung- Hai Bà Trưng- Hà Nội</span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">- Tên tài khoản: Công ty TNHH công nghệ tin học Thu Thảo</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Số tài khoản VND: 1500.201.082.444</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>Mã citad:<span class="Apple-converted-space">&nbsp;</span></strong><strong>01204003</strong></span></p>
<p style="font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>4.<span style="font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span></span></strong><strong>Ngân hàng TMCP Kỹ Thương Việt Nam – Trung tâm giao dịch Hội sở</strong></span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span></strong>Địa chỉ: 191 Bà Triệu- Hai Bà Trưng- Hà Nội</span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Tên tài khoản: Công ty TNHH công nghệ tin học Thu Thảo</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Số TK VND: 108.2361.0928.999</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>Mã citad:<span class="Apple-converted-space">&nbsp;</span></strong><strong>79310001</strong></span></p>
<p style="font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>Ngân hàng TMCP Đầu tư và phát triển Việt Nam- Chi nhánh Cầu Giấy</strong></span></p>
<p style="margin: 0px 0px 0px 1.5pt; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">&nbsp;&nbsp;&nbsp;&nbsp; Địa chỉ:&nbsp; 106 Hoàng Quốc Việt – Cầu Giấy- Hà Nội</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Tên TK: Công ty TNHH công nghệ tin học Thu Thảo</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Số TK: 2151.000.1289.241</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>Mã ngân hàng:<span class="Apple-converted-space">&nbsp;</span></strong><strong>01202010</strong></span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>ĐT:<span class="Apple-converted-space">&nbsp;</span></strong>3755 6910<strong>&nbsp;</strong></span></p>
<span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: arial,helvetica,sans-serif;"><strong>6/ </strong></span></span><strong><span style="font-family: arial,helvetica,sans-serif;">Ngân hàng TMCP Á Châu- Chi nhánh Hà Nội</span></strong></span>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">&nbsp;</span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">&nbsp; &nbsp; &nbsp; &nbsp;- &nbsp; &nbsp;Địa chỉ: 184 - 186 Bà Triệu- Hai Bà Trưng- Hà Nội</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Tên Tài khoản: Công ty TNHH công nghệ tin học Thu Thảo</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Số TK: 174420119</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Mã ngân hàng: 01307001</span></p>
<p style="font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">7.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span><strong>Ngân Hàng TNHH một thành viên ANZ (Việt Nam)- Trụ sở chính</strong></span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">- Địa chỉ: 13 Hai Bà Trưng, Hà Nội, Việt Nam</span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">- Tên tài khoản: Công ty TNHH công nghệ tin học Thu Thảo</span></p>
<p style="margin: 0px; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">- Số TK&nbsp; VND : 7875567</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Số Tk USD:&nbsp; 7875589</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Mã ngân hàng:: 79602001</span></p>
<p style="font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>8.<span style="font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span></span></strong><strong>Ngân hàng TMCP Tiên Phong- PGD Nam Hà Nội</strong></span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>Tên Tài khoản: Công ty TNHH công nghệ tin học Thu Thảo</span></p>
<p style="margin: 0px 0px 0px 0.5in; font-size: 12.8px; font-weight: normal; font-family: arial,sans-serif; color: #222222; text-align: start;"><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;">-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="Apple-converted-space">&nbsp;</span>&nbsp;Số TK VND: 00118668001</span></p>
</td>
</tr>
</tbody>
</table>
<p><span style="font-family: arial,helvetica,sans-serif; font-size: medium; color: #000000;"><strong>&nbsp;</strong></span></p>
<br> <strong>Công ty TNHH công nghệ tin học Thu Thảo</strong> <br> Showroom 1: Số 10 Ngõ 117 Thái Hà, Đống Đa, Hà Nội. <br>  Tel: (04) 3537 9690   Fax (04) 3537 9692  <br> Email: thaovoigtvt2909@ gmail.com </span></span></p>
</div>
                  	
                
            </div><!--float_r-->
        </div><!--other_news-->
    </div><!--detail_news-->
</div>